Log Peer Validator Timeout Messages
deso-protocol/core pull request #1058
Opened 2024-02-21 15:29 UTC by tholonious

2024-02-21 15:29 UTC, tholonious commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/deso-protocol/core/1058?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#1058** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/1058?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1057** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/1057?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `feature/pos-networking-and-syncing`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/1058?utm_source=stack-comment).

2024-02-22 16:31 UTC, lazynina requested changes

2024-02-22 16:31 UTC, lazynina commented on lib/pos_consensus.go
> +	glog.Infof("FastHotStuffConsensus.HandleLocalTimeoutEvent: Received timeout msg: %s", msg.ToString())
```suggestion
	glog.V(2).Infof("FastHotStuffConsensus.HandleLocalTimeoutEvent: Received timeout msg: %s", msg.ToString())
```

2024-02-22 17:15 UTC, lazynina approved these changes

2024-02-22 17:38 UTC, merged