NewUtxoView never returns an error
deso-protocol/core pull request #1197
Opened 2024-04-10 20:46 UTC by lazynina

2024-04-11 21:08 UTC, tholonious requested changes

2024-04-11 21:08 UTC, tholonious commented on lib/pos_blockchain.go
>  func (bc *Blockchain) GetCommittedTipView() (*UtxoView, error) {
May as well update this too
```suggestion
func (bc *Blockchain) GetCommittedTipView() *UtxoView {
```

2024-04-11 21:10 UTC, tholonious commented on lib/pos_blockchain.go
>  func (bc *Blockchain) GetCommittedTipView() (*UtxoView, error) {
Nvm, I see this is updated in the next PR. Please ignore

2024-04-12 00:05 UTC, tholonious approved these changes

2024-04-12 00:07 UTC, lazynina commented
### Merge activity

* **Apr 11, 8:07 PM EDT**: @lazynina started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/1197).

2024-04-12 00:10 UTC, merged