Convert DAO coin limit order price from BigFloat to Uint256.
deso-protocol/core pull request #266
Opened 2022-03-16 20:19 UTC by mattfoley8

2022-03-16 20:37 UTC, lazynina requested changes
I think we may have to flip the ordering in get next orders to fill and the related db utils functions since we've inverted the definition of PriceNanos

2022-03-16 21:39 UTC, mattfoley8 commented on lib/block_view_dao_coin_limit_order.go
> +			if desoBalanceNanos < requestedOrderTotalCost.Uint64() {
Yes.

2022-03-16 21:40 UTC, mattfoley8 commented on lib/block_view_dao_coin_limit_order.go
> +	requestedOrderTotalCost := uint256.NewInt().Mul(txMeta.PriceNanosPerDenominatedCoin, txMeta.Quantity)
Yeah, that's right. I still need to figure out what this updated math is. I.e. how to calculate an order's total cost using `PriceNanosPerDenominatedCoin` and `Quantity`.

2022-03-17 15:47 UTC, lazynina approved these changes

2022-03-17 15:49 UTC, merged