Access Groups
deso-protocol/core pull request #412
Opened 2022-11-04 23:59 UTC by AeonSw4n

2022-11-23 03:38 UTC, lazynina reviewed
Checking in the first chunk of my review. Basically looked through the block_view files (need to dig into tests a little bit more), but wanted to get you the feedback I have so far.

Still need to look into
1. db_utils
2. postgres
3. network
4. server

2022-11-23 03:38 UTC, lazynina commented on lib/blockchain.go
> +		// We're not storing blocks in postgres, so we should store the actual blocks in the badgerdb.
Well it does look like we are storing blocks in the upsert above. is the issue that we're just not checking postgres in GetBlock?

2022-11-23 03:38 UTC, lazynina commented on lib/blockchain.go
> +				if err := bc.postgres.UpsertChain(MAIN_CHAIN, &prevHash); err != nil {
it would be better if we could move this postgres v badger logic to the db adapter

2022-11-23 03:38 UTC, lazynina commented on lib/blockchain.go
> +			if bc.postgres != nil {
would prefer to move pg v. badger logic to db adapter.

2022-11-23 03:38 UTC, lazynina commented on lib/db_adapter.go
> +		return nil, nil
why glog it when this function returns an error?

2022-11-23 03:38 UTC, lazynina commented on lib/db_adapter.go
> +		return pgAccessGroup.ToAccessGroupEntry(), nil
you can update `ToAccessGroupEntry` to check if the pgAccessGroup is nil and we can simplify this block of code to be
`return pgAccessGroup.ToAccessGroupEntry()`

2022-11-23 03:38 UTC, lazynina commented on lib/mempool.go
> +	// TODO: Do we need something for access groups and new dm/group chats here?
yes please

2022-11-24 22:26 UTC, AeonSw4n commented on lib/block_view_flush.go
> +	numPut := 0
Cause otherwise they get reset to 0 everytime lol

2022-12-06 03:16 UTC, lazynina requested changes

2022-12-06 03:16 UTC, lazynina commented on lib/db_utils.go
> +	if err != nil && err != badger.ErrKeyNotFound {
when would we receive a ErrKeyNotFound here?

2022-12-06 03:16 UTC, lazynina commented on lib/db_utils.go
> +	prefix := _dbKeyForAccessGroupEntry(*accessGroupOwnerPublicKey, *accessGroupKeyName)
what happens if we're passed nil for either param?

2022-12-06 03:16 UTC, lazynina commented on lib/db_utils.go
> +	prefix := _dbKeyForAccessGroupEntry(*accessGroupOwnerPublicKey, *accessGroupKeyName)
what happens if we're passed nil for either param?

2022-12-06 03:16 UTC, lazynina commented on lib/db_utils.go
> +	prefix := _dbKeyForAccessGroupEntry(*accessGroupEntry.AccessGroupOwnerPublicKey, *accessGroupEntry.AccessGroupKeyName)
what happens if we're given a nil accessGroupEntry?

2022-12-06 03:16 UTC, lazynina commented on lib/db_utils.go
> +func _dbSeekPrefixForAccessGroupMemberEntry(accessGroupMemberPublicKey PublicKey) []byte {
might we want a seek function for accessGroupMember + groupOwner? "what are all my group chat with User X" use case. not critical now, but food for thought.

2022-12-06 03:16 UTC, lazynina commented on lib/db_utils.go
> +		glog.Errorf("DBPutAccessGroupMemberEntryWithTxn: groupKeyName is empty")
what do we want to do here? do we save base key? if so, I would remove the if statement. reflect.DeepEqual is expensive relatively.

2022-12-06 03:16 UTC, lazynina commented on lib/db_utils.go
> +	prefix := _dbKeyForAccessGroupMemberEntry(
Isn't this really the key, not a prefix?

2022-12-06 03:16 UTC, lazynina commented on lib/db_utils.go
> +	prefix := _dbKeyForAccessGroupMemberEntry(accessGroupMemberPublicKey, accessGroupOwnerPublicKey, accessGroupKeyName)
isn't this a key, not a prefix?

2022-12-06 03:16 UTC, lazynina commented on lib/db_utils.go
> +	if len(keysFound) > 0 && bytes.Compare(startKey, keysFound[0]) == 0 {
This seems a little hacky

2022-12-06 03:16 UTC, lazynina commented on lib/db_utils.go
> +		memberPublicKeyBytes := key[len(prefix):]
we must be passing in the empty public key to get the first page, right?

2022-12-06 03:16 UTC, lazynina commented on lib/db_utils.go
> +	for ii := 1; ii < len(accessGroupMembers); ii++ {
this seems unnecessary since badger is sorted and these compares could be costly.

2022-12-29 14:01 UTC, AeonSw4n commented on lib/block_view_access_group.go
> +	}
I think that was just some old code, fixed now.

2022-12-30 10:56 UTC, AeonSw4n reviewed
First pass on @lazynina review

2023-01-20 06:45 UTC, diamondhands0 approved these changes

2023-01-20 07:20 UTC, merged