Add epoch data type.
deso-protocol/core pull request #514
Opened 2023-04-28 15:21 UTC by mattfoley8

2023-04-28 16:50 UTC, tholonious requested changes

2023-04-28 16:50 UTC, tholonious commented on lib/pos_epoch.go
> +	LastBlockHeightInEpoch uint64
Equally clear but a bit more concise
```suggestion
	FinalBlockHeight uint64
```

2023-05-01 18:54 UTC, lazynina requested changes

2023-05-01 18:54 UTC, lazynina commented on lib/pos_epoch.go
> +func (bav *UtxoView) SetCurrentEpochEntry(epochEntry *EpochEntry, blockHeight uint64) error {
typically like to have these setters just glog the errors instead of returning them. Also these are typically private functions.

2023-05-01 18:54 UTC, lazynina commented on lib/pos_epoch.go
> +	if bav.Snapshot != nil {
not sure if this is the correct place for this logic. I'll need to think about its proper place a little more. I think it should be handled in `FlushToDbWithTxn`

2023-05-01 18:54 UTC, lazynina commented on lib/pos_epoch.go
> +func (bav *UtxoView) DeleteCurrentEpochEntry() {
private

2023-05-03 19:55 UTC, lazynina commented on lib/pos_epoch.go
> +		return nil
since this function does return an error, should we just return the error instead of glogging?

2023-05-03 20:26 UTC, lazynina approved these changes

2023-05-04 14:29 UTC, merged