PoS Deprecate GlobalActiveStakeAmountNanos
deso-protocol/core pull request #584
Opened 2023-07-10 22:47 UTC by tholonious

2023-07-10 22:47 UTC, tholonious commented
Current dependencies on/for this PR:
* feature/proof-of-stake
  * **PR #579** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/579" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #583** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/583" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #584** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/584" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/584?utm_source=stack-comment).

2023-07-11 19:03 UTC, lazynina requested changes

2023-07-11 19:03 UTC, lazynina commented on lib/block_view_validator.go
> +	for _, validatorEntry := range validatorEntries {
Is the assumption that the caller of this function is responsible for defining the validators to include? This function does not take validator status into consideration. We should add a comment on top of this function.

2023-07-11 19:12 UTC, lazynina approved these changes

2023-07-11 19:20 UTC, merged