WIP: Limit number of chunks in operation channel to reduce hypersync memor…
deso-protocol/core pull request #604
Opened 2023-07-14 04:20 UTC by superzordon

…y consumption

2023-07-14 20:04 UTC, AeonSw4n requested changes

2023-07-14 20:04 UTC, AeonSw4n commented on cmd/node.go
> +	opts := badger.DefaultOptions(dbDir)
This is a significant change that reduces memory by 30-40 GB. But also comes at tradeoffs of smaller Badger transactions. Could you blocksync with this change and see if everything works?

2023-07-20 20:55 UTC, diamondhands0 approved these changes

2023-07-27 20:31 UTC, lazynina approved these changes

2023-07-27 20:41 UTC, merged