Distribute Staking Rewards on Epoch Transition
deso-protocol/core pull request #607
Opened 2023-07-14 20:03 UTC by tholonious

2023-07-14 20:03 UTC, tholonious commented
Current dependencies on/for this PR:
* feature/proof-of-stake
  * **PR #579** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/579" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #598** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/598" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #605** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/605" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #606** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/606" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #607** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/607" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/607?utm_source=stack-comment).

2023-07-14 20:03 UTC, tholonious commented
Current dependencies on/for this PR:
* feature/proof-of-stake
  * **PR #579** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/579" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #598** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/598" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #605** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/605" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #606** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/606" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #607** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/607" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/607?utm_source=stack-comment).

2023-07-17 17:22 UTC, lazynina requested changes

2023-07-17 17:22 UTC, lazynina commented on lib/pos_staking_rewards.go
> +		// TODO: _addBalance returns a UtxoOperation. Do we want to do anything with it?
we should probably return an array of utxo operations from this function. similar to how we have a utxo operation when we delete the expired nonces, we'll want to save this state somehow.

2023-07-17 21:00 UTC, lazynina requested changes

2023-07-18 00:42 UTC, lazynina approved these changes

2023-07-18 13:38 UTC, merged