Fast HotStuff Timeout Msg Storage
deso-protocol/core pull request #650
Opened 2023-08-31 20:46 UTC by tholonious

2023-09-09 00:12 UTC, AeonSw4n requested changes

2023-09-11 14:32 UTC, tholonious commented on consensus/utils.go
> +	highQCViewBytes := []byte(fmt.Sprintf("%d", highQCView))
> For instance (view, highQCView) of (1, 11) encodes the same as (11, 1)

Good catch. Yeah the binary.LittleEndian.PutUint64 or binary.BigEndian.PutUint64 resolves the many-to-one encoding issue

2023-09-11 14:34 UTC, tholonious commented on consensus/event_loop.go
> +
Sha3 is fine here. It's broadly used elsewhere in the codebase anyway

2023-09-11 14:40 UTC, tholonious commented on consensus/utils.go
> +	return sha256.Sum256(append(viewBytes, highQCViewBytes[:]...))
That was a typo. Good catch

2023-09-11 23:00 UTC, AeonSw4n approved these changes

2023-09-11 23:06 UTC, merged