PoS Block Producer: Data Structure
deso-protocol/core pull request #704
Opened 2023-10-02 13:43 UTC by AeonSw4n

2023-10-02 13:44 UTC, AeonSw4n commented
Current dependencies on/for this PR:
* feature/proof-of-stake
  * **PR #578** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/578" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #671** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/671" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #676** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/676" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #700** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/700" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #701** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/701" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #702** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/702" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #703** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/703" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #704** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/704" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
        * **PR #689** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/689" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #673** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/673" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #672** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/672" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/704?utm_source=stack-comment).

2023-10-02 13:44 UTC, AeonSw4n commented
Current dependencies on/for this PR:
* feature/proof-of-stake
  * **PR #578** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/578" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #671** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/671" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #676** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/676" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #700** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/700" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #701** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/701" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #702** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/702" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #703** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/703" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #704** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/704" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
        * **PR #689** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/689" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #673** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/673" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #672** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/672" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/704?utm_source=stack-comment).

2023-10-09 21:04 UTC, tholonious requested changes
LGTM aside from the propposerRandomSeedHash param change

2023-10-09 21:04 UTC, tholonious commented on lib/pos_block_producer.go
> +func (pbp *PosBlockProducer) CreateUnsignedBlock(latestBlockView *UtxoView, newBlockHeight uint64, view uint64,
```suggestion
func (pbp *PosBlockProducer) CreateUnsignedBlock(latestBlockView *UtxoView, newBlockHeight uint64, view uint64, proposerRandomSeedHash *RandomSeedHash,
```

2023-10-09 21:04 UTC, tholonious commented on lib/pos_block_producer.go
> +func (pbp *PosBlockProducer) CreateUnsignedTimeoutBlock(latestBlockView *UtxoView, newBlockHeight uint64, view uint64,
```suggestion
func (pbp *PosBlockProducer) CreateUnsignedTimeoutBlock(latestBlockView *UtxoView, newBlockHeight uint64, view uint64, proposerRandomSeedHash *RandomSeedHash,
```

2023-10-09 21:04 UTC, tholonious commented on lib/pos_block_producer.go
> +	proposerRandomSeedHash  *RandomSeedHash
```suggestion
```

2023-10-10 01:28 UTC, tholonious approved these changes

2023-10-10 01:43 UTC, merged