add validateBlockHeight function and tests
deso-protocol/core pull request #706
Opened 2023-10-02 21:25 UTC by lazynina

2023-10-02 21:26 UTC, lazynina commented
Current dependencies on/for this PR:
* feature/proof-of-stake
  * **PR #649** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/649" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #686** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/686" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #705** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/705" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #706** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/706" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/706?utm_source=stack-comment).

2023-10-10 16:54 UTC, tholonious requested changes

2023-10-10 16:54 UTC, tholonious commented on lib/pos_blockchain.go
> +	if desoBlock.Header.Height != bc.GetBestChainTip().Header.Height+1 {
This should make sure that the block's height is +1 of its parent's block height. This also addresses the fork question below.

2023-10-10 16:54 UTC, tholonious commented on lib/pos_blockchain.go
> +	// TODO: What if this is a fork? Should this check be more lenient and only check
Not sure if you do this anywhere else. But you'll also want to verify that the block height is past the PoS cutover fork height somewhere. This feels like a natural place to make that check

2023-10-11 18:13 UTC, merged