Lockups derived key spending limit implementation.
deso-protocol/core pull request #716
Opened 2023-10-04 22:31 UTC by poolcoke

2023-10-04 22:31 UTC, poolcoke commented
Current dependencies on/for this PR:
* feature/coin-lockups
  * **PR #678** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/678" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #679** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/679" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #680** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/680" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #681** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/681" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #682** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/682" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #683** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/683" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #684** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/684" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #716** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/716" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/716?utm_source=stack-comment).

2023-10-10 21:55 UTC, lazynina requested changes
Please update `CheckIfValidUnlimitedSpendingLimit` in `network.go` and update the `AssertDependencyStructFieldNumbers` to check for 14 fields.

2023-10-10 23:34 UTC, poolcoke commented
Fixed

2023-10-11 00:05 UTC, lazynina requested changes

2023-10-11 00:06 UTC, poolcoke commented on lib/block_view.go
> +		if txnMeta.LockupYieldDurationNanoSecs > 0 {
Yeah good point. Could be some sort of an exploit where a balance is drained via fees.

2023-11-14 22:50 UTC, closed without merging