Handle And Broadcast Local Timeout Signal
deso-protocol/core pull request #779
Opened 2023-11-02 17:42 UTC by tholonious

2023-11-02 17:42 UTC, tholonious commented
Current dependencies on/for this PR:
* feature/pos-networking-and-syncing
  * **PR #778** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/778" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #779** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/779" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/779?utm_source=stack-comment).

2023-11-07 18:27 UTC, tholonious commented on lib/pos_consensus_controller.go
> +	// timeoutMsg.PublicKey = <ECDSA public key here>
@AeonSw4n, @lazynina we need the validator's ECDSA public key available in this controller for timeout and vote construction. We'll similarly need it for block construction. A few of options in how we can do it:
- We pull it from the on-chain state by constructing a UtxoView at the current tip to fetch the current validator set's ValidatorEntries
- We maintain a cached version of the validator set in this controller for each block height. We need to compute the validator set for each safe block anyway when processing each incoming block
- The validator's ECDSA public key is configured along with the BLS signer metadata and passed along into the controller

My preference would be option 2. LMK if you have other thoughts

2023-11-07 19:01 UTC, lazynina requested changes
LGTM - just some nits on comments.

2023-11-07 19:11 UTC, tholonious commented on lib/pos_consensus_controller.go
> +	// timeoutMsg.PublicKey = <ECDSA public key here>
Sounds good. I'll follow up with another PR for it

2023-11-07 19:46 UTC, lazynina approved these changes

2023-11-08 17:55 UTC, merged