Add ConsensusController Utility to Fetch Validator Set For Blocks
deso-protocol/core pull request #819
Opened 2023-11-15 18:43 UTC by tholonious

Cleanup

Address Nina's comments

2023-11-15 18:43 UTC, tholonious commented
Current dependencies on/for this PR:
* feature/pos-networking-and-syncing
  * **PR #819** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/819?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/819?utm_source=stack-comment).

2023-11-15 19:41 UTC, lazynina requested changes

2023-11-15 19:41 UTC, lazynina commented on lib/pos_consensus_controller.go
> +		}
So this function gets us half way there, but I think what we want to do is create a single utxo view struct without connecting any uncommitted blocks. We should have all the snapshot data available in the database that we want and connecting parents only really helps us figure out "current epoch". 

What I think we want to do is the following:
1. create a single vanilla utxo view `NewUtxoView(cc.blockchain.db, cc.blockchain.params, nil, cc.blockchain.snapshot, nil)` or maybe not nil for event manager, but that's up to you.
2. `currentEpochEntry, err := utxoView.GetCurrentEpochEntry()` 
3. For each block,
-  if `currentEpochEntry.ContainsBlockHeight(block.Height)`, use current epoch to compute snapshotAtEpochNumber
-  if not , we know must be in the next epoch. We can simulate the epoch using a function I wrote, basically just ripped out of the rollover logic,  called `computeNextEpochEntry`. Confirm block is in the next epoch and lookup snapshotAtEpochNumber for that computed epoch.
- Look up all validators using `GetAllSnapshotValidatorSetEntriesByStakeAtEpochNumber` (all in my pos-process-block stack)

2023-11-16 00:26 UTC, lazynina approved these changes

2023-11-16 00:26 UTC, lazynina commented on lib/pos_consensus_controller.go
> +	// TODO: Do we need to pass a pointer to the Postgres object here?
We won't need to do this actually!
```suggestion
```

2023-11-16 00:35 UTC, merged