PoS RemoteNodeIndexerManager
deso-protocol/core pull request #859
Opened 2023-12-07 13:25 UTC by AeonSw4n

2023-12-07 13:25 UTC, AeonSw4n commented
Current dependencies on/for this PR:
* feature/proof-of-stake
  * **PR #830** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/830?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #768** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/768?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #857** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/857?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #858** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/858?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #859** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/859?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #792** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/792?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #793** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/793?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/859?utm_source=stack-comment).

2023-12-07 13:25 UTC, AeonSw4n commented
Current dependencies on/for this PR:
* feature/proof-of-stake
  * **PR #830** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/830?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #768** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/768?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #857** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/857?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #858** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/858?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #859** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/859?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #792** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/792?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #793** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/793?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/859?utm_source=stack-comment).

2023-12-18 16:22 UTC, tholonious requested changes

2023-12-18 16:22 UTC, tholonious commented on lib/pos_remote_node_indexer_manager.go
Please merge the RemoteNodeIndexerManager and RemoteNodeIndexer structs. They are single instance nested structs that are highly coupled in what they are intended to do. The manager is pass-through struct to the indexer. Merging them will make your code more concise and make it clearer to readers what the overall intent of the public interface for the indexer manager is.

2023-12-29 15:00 UTC, closed without merging