PoS NetworkManager Address
deso-protocol/core pull request #957
Opened 2024-01-29 03:38 UTC by AeonSw4n

2024-01-29 03:38 UTC, AeonSw4n commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/deso-protocol/core/957?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `feature/pos-networking-and-syncing`
  * **PR #942** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/942?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #943** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/943?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #944** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/944?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #945** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/945?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #957** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/957?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
          * **PR #912** <a href="https://app.graphite.dev/github/pr/deso-protocol/core/912?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/deso-protocol/core/957?utm_source=stack-comment).

2024-01-29 17:14 UTC, tholonious requested changes

2024-01-29 17:14 UTC, tholonious commented on lib/server.go
> +			if err := rn.SendMessage(&MsgDeSoAddr{
nit, clean up nesting for readability
```suggestion
			addrMsg := MsgDeSoAddr{
```

2024-01-29 17:14 UTC, tholonious commented on lib/server.go
> +			}); err != nil {
```suggestion
			if err := rn.SendMessage(&addrMsg); err != nil {
```

2024-01-29 17:14 UTC, tholonious commented on lib/server.go
> +					if err := rn.SendMessage(&MsgDeSoAddr{
nit: clean up nesting for readability
```suggestion
					addrMsg := MsgDeSoAddr{
```

2024-01-29 17:14 UTC, tholonious commented on lib/server.go
> +					}); err != nil {
```suggestion
					if err := rn.SendMessage(&addrMsg}); err != nil {
```

2024-01-29 17:14 UTC, tholonious commented on lib/server.go
> +func (srv *Server) _handleAddrMessage(origin *Peer, desoMsg DeSoMessage) {
nit: pp is the common and accepted variable name for the Peer type in incoming messages handlers. Revert this for consistency with the rest of the code
```suggestion
func (srv *Server) _handleAddrMessage(pp *Peer, desoMsg DeSoMessage) {
```

2024-01-30 04:02 UTC, AeonSw4n commented on lib/connection_manager.go
> -	newPeerChan  chan *Peer
It's redundant now with the NetworkManager design. Peer is created directly from an established outbound/inbound connection in the same thread, and there is no need for the `newPeerChan` indirection.

2024-01-30 05:13 UTC, merged